// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna1/encodings.h"
#include <string>

namespace rocjitsu {
namespace rdna1 {

namespace {
std::string flat_mnemonic(std::string_view mnemonic, int seg) {
  // seg: 0=FLAT, 1=SCRATCH, 2=GLOBAL
  if (seg == 1 && mnemonic.substr(0, 5) == "flat_")
    return std::string("scratch_").append(mnemonic.substr(5));
  if (seg == 2 && mnemonic.substr(0, 5) == "flat_")
    return std::string("global_").append(mnemonic.substr(5));
  return std::string(mnemonic);
}
} // namespace

Sop1::Sop1(std::string_view mnemonic, const Sop1MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Sop1::default_encoding() { return inst_.ssrc0 != 255; }

bool Sop1::has_lit_0() { return inst_.ssrc0 == 255; }

Sopc::Sopc(std::string_view mnemonic, const SopcMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Sopc::default_encoding() { return inst_.ssrc0 != 255 && inst_.ssrc1 != 255; }

bool Sopc::has_lit_0() { return inst_.ssrc0 == 255 && inst_.ssrc1 != 255; }

bool Sopc::has_lit_1() { return inst_.ssrc0 != 255 && inst_.ssrc1 == 255; }

bool Sopc::has_lit_0_has_lit_1() { return inst_.ssrc0 == 255 && inst_.ssrc1 == 255; }

Sopp::Sopp(std::string_view mnemonic, const SoppMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Sopp::default_encoding() { return true; }

Sopk::Sopk(std::string_view mnemonic, const SopkMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding() || hasImpliedLiteral())
    size_ += sizeof(MachineInst);
  if (hasImpliedLiteral())
    literal_ = reinterpret_cast<const uint32_t *>(inst)[1];
}

bool Sopk::default_encoding() { return true; }

bool Sopk::hasImpliedLiteral() { return inst_.op == 21; }

Sop2::Sop2(std::string_view mnemonic, const Sop2MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Sop2::default_encoding() { return inst_.ssrc0 != 255 && inst_.ssrc1 != 255; }

bool Sop2::has_lit_0() { return inst_.ssrc0 == 255 && inst_.ssrc1 != 255; }

bool Sop2::has_lit_1() { return inst_.ssrc0 != 255 && inst_.ssrc1 == 255; }

bool Sop2::has_lit_0_has_lit_1() { return inst_.ssrc0 == 255 && inst_.ssrc1 == 255; }

Smem::Smem(std::string_view mnemonic, const SmemMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Smem::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (inst->glc)
    out += " glc";
  if (inst->dlc)
    out += " dlc";
}

Vop1::Vop1(std::string_view mnemonic, const Vop1MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Vop1::default_encoding() {
  return inst_.src0 != 250 && inst_.src0 != 233 && inst_.src0 != 234 && inst_.src0 != 255 &&
         inst_.src0 != 249;
}

bool Vop1::has_lit() { return inst_.src0 == 255; }

Vopc::Vopc(std::string_view mnemonic, const VopcMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Vopc::default_encoding() {
  return inst_.src0 != 250 && inst_.src0 != 233 && inst_.src0 != 234 && inst_.src0 != 255 &&
         inst_.src0 != 249;
}

bool Vopc::has_lit() { return inst_.src0 == 255; }

Vop2::Vop2(std::string_view mnemonic, const Vop2MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding() || hasImpliedLiteral())
    size_ += sizeof(MachineInst);
  if (hasImpliedLiteral())
    literal_ = reinterpret_cast<const uint32_t *>(inst)[1];
}

bool Vop2::default_encoding() {
  return inst_.src0 != 250 && inst_.src0 != 233 && inst_.src0 != 234 && inst_.src0 != 255 &&
         inst_.src0 != 249;
}

bool Vop2::has_lit() { return inst_.src0 == 255; }

bool Vop2::hasImpliedLiteral() {
  return inst_.op == 32 || inst_.op == 33 || inst_.op == 44 || inst_.op == 45 || inst_.op == 55 ||
         inst_.op == 56;
}

Vintrp::Vintrp(std::string_view mnemonic, const VintrpMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Vintrp::default_encoding() { return true; }

Vop3::Vop3(std::string_view mnemonic, const Vop3MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

bool Vop3::has_lit_0() { return inst_.src0 == 255 && inst_.src1 != 255 && inst_.src2 != 255; }

bool Vop3::has_lit_1() { return inst_.src0 != 255 && inst_.src1 == 255 && inst_.src2 != 255; }

bool Vop3::has_lit_0_has_lit_1() {
  return inst_.src0 == 255 && inst_.src1 == 255 && inst_.src2 != 255;
}

bool Vop3::has_lit_2() { return inst_.src0 != 255 && inst_.src1 != 255 && inst_.src2 == 255; }

bool Vop3::has_lit_0_has_lit_2() {
  return inst_.src0 == 255 && inst_.src1 != 255 && inst_.src2 == 255;
}

bool Vop3::has_lit_1_has_lit_2() {
  return inst_.src0 != 255 && inst_.src1 == 255 && inst_.src2 == 255;
}

bool Vop3::has_lit_0_has_lit_1_has_lit_2() {
  return inst_.src0 == 255 && inst_.src1 == 255 && inst_.src2 == 255;
}

Vop3p::Vop3p(std::string_view mnemonic, const Vop3pMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

bool Vop3p::has_lit_0() { return inst_.src0 == 255 && inst_.src1 != 255 && inst_.src2 != 255; }

bool Vop3p::has_lit_1() { return inst_.src0 != 255 && inst_.src1 == 255 && inst_.src2 != 255; }

bool Vop3p::has_lit_0_has_lit_1() {
  return inst_.src0 == 255 && inst_.src1 == 255 && inst_.src2 != 255;
}

bool Vop3p::has_lit_2() { return inst_.src0 != 255 && inst_.src1 != 255 && inst_.src2 == 255; }

bool Vop3p::has_lit_0_has_lit_2() {
  return inst_.src0 == 255 && inst_.src1 != 255 && inst_.src2 == 255;
}

bool Vop3p::has_lit_1_has_lit_2() {
  return inst_.src0 != 255 && inst_.src1 == 255 && inst_.src2 == 255;
}

bool Vop3p::has_lit_0_has_lit_1_has_lit_2() {
  return inst_.src0 == 255 && inst_.src1 == 255 && inst_.src2 == 255;
}

Ds::Ds(std::string_view mnemonic, const DsMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

Mubuf::Mubuf(std::string_view mnemonic, const MubufMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Mubuf::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (inst->offen)
    out += " offen";
  if (inst->idxen)
    out += " idxen";
  if (inst->offset)
    out += " offset:" + std::to_string(inst->offset);
  if (inst->glc)
    out += " glc";
  if (inst->dlc)
    out += " dlc";
  if (inst->slc)
    out += " slc";
  if (inst->lds)
    out += " lds";
}

Mtbuf::Mtbuf(std::string_view mnemonic, const MtbufMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Mtbuf::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (inst->offen)
    out += " offen";
  if (inst->offset)
    out += " offset:" + std::to_string(inst->offset);
  if (inst->glc)
    out += " glc";
  if (inst->dlc)
    out += " dlc";
  if (inst->slc)
    out += " slc";
}

Mimg::Mimg(std::string_view mnemonic, const MimgMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

bool Mimg::has_nsa_1() { return inst_.nsa == 1; }

bool Mimg::has_nsa_2() { return inst_.nsa == 2; }

bool Mimg::has_nsa_3() { return inst_.nsa == 3; }

Exp::Exp(std::string_view mnemonic, const ExpMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
}

Flat::Flat(std::string_view mnemonic, const FlatMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>("", exec_fn), inst_(*inst),
      owned_mnemonic_(flat_mnemonic(mnemonic, inst->seg)) {
  mnemonic_ = owned_mnemonic_;
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Flat::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (inst->offset)
    out += " offset:" + std::to_string(inst->offset);
  if (inst->glc)
    out += " glc";
  if (inst->dlc)
    out += " dlc";
  if (inst->slc)
    out += " slc";
}

void Flat::implicit_uses(RegisterSet &uses) const {
  if (inst_.saddr == 0x7F)
    return;
  if (inst_.seg == 1) {
    uses.expand(RegisterRef{RegClass::SGPR, static_cast<uint16_t>(inst_.saddr), 1});
  } else if (inst_.seg == 2) {
    uses.expand(RegisterRef{RegClass::SGPR, static_cast<uint16_t>(inst_.saddr), 2});
  }
}

Vop3SdstEnc::Vop3SdstEnc(std::string_view mnemonic, const Vop3SdstEncMachineInst *inst,
                         ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

} // namespace rdna1
} // namespace rocjitsu
