// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_RDNA3_5_ENCODINGS_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_RDNA3_5_ENCODINGS_H_

#include "rocjitsu/isa/arch/amdgpu/rdna3_5/isa.h"
#include "rocjitsu/isa/arch/amdgpu/rdna3_5/machine_insts.h"
#include "rocjitsu/isa/arch/amdgpu/shared/dpp_sdwa_ops.h"
#include "rocjitsu/isa/instruction.h"
#include <string>
#include <string_view>

namespace rocjitsu {
namespace rdna3_5 {

class Sop1 : public IsaInstruction<Isa> {
public:
  Sop1(std::string_view mnemonic, const Sop1MachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  bool has_lit_0();
  using OpEncoding = Sop1MachineInst;
  const OpEncoding inst_;
};

class Sopc : public IsaInstruction<Isa> {
public:
  Sopc(std::string_view mnemonic, const SopcMachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  bool has_lit_0();
  bool has_lit_1();
  bool has_lit_0_has_lit_1();
  using OpEncoding = SopcMachineInst;
  const OpEncoding inst_;
};

class Sopp : public IsaInstruction<Isa> {
public:
  Sopp(std::string_view mnemonic, const SoppMachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  using OpEncoding = SoppMachineInst;
  const OpEncoding inst_;
};

class Sopk : public IsaInstruction<Isa> {
public:
  Sopk(std::string_view mnemonic, const SopkMachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  bool hasImpliedLiteral();
  using OpEncoding = SopkMachineInst;
  const OpEncoding inst_;
  uint32_t literal_ = 0;
};

class Sop2 : public IsaInstruction<Isa> {
public:
  Sop2(std::string_view mnemonic, const Sop2MachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  bool has_lit_0();
  bool has_lit_1();
  bool has_lit_0_has_lit_1();
  bool hasImpliedLiteral();
  using OpEncoding = Sop2MachineInst;
  const OpEncoding inst_;
  uint32_t literal_ = 0;
};

class Smem : public IsaInstruction<Isa> {
public:
  Smem(std::string_view mnemonic, const SmemMachineInst *inst, ExecuteFn exec_fn);
  void build_modifiers(std::string &out) const override;
  using OpEncoding = SmemMachineInst;
  const OpEncoding inst_;
};

class Vop1 : public IsaInstruction<Isa> {
public:
  Vop1(std::string_view mnemonic, const Vop1MachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  bool has_lit();
  using OpEncoding = Vop1MachineInst;
  const OpEncoding inst_;
  uint32_t dpp_ctrl_ = 0;
  uint32_t dpp_row_mask_ = 0xF;
  uint32_t dpp_bank_mask_ = 0xF;
  uint32_t dpp_bound_ctrl_ = 0;
  std::unique_ptr<DppOperand> dpp_src0_;
  std::unique_ptr<DppOperand> dpp_src1_;
  uint32_t sdwa_src0_sel_ = amdgpu::sdwa::DWORD;
  bool sdwa_src0_sext_ = false;
  uint32_t sdwa_src1_sel_ = amdgpu::sdwa::DWORD;
  bool sdwa_src1_sext_ = false;
  uint32_t sdwa_dst_sel_ = amdgpu::sdwa::DWORD;
  uint32_t sdwa_dst_unused_ = 0;
  bool sdwa_clamp_ = false;
};

class Vopc : public IsaInstruction<Isa> {
public:
  Vopc(std::string_view mnemonic, const VopcMachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  bool has_lit();
  using OpEncoding = VopcMachineInst;
  const OpEncoding inst_;
};

class Vop2 : public IsaInstruction<Isa> {
public:
  Vop2(std::string_view mnemonic, const Vop2MachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  bool has_lit();
  bool hasImpliedLiteral();
  using OpEncoding = Vop2MachineInst;
  const OpEncoding inst_;
  uint32_t literal_ = 0;
  uint32_t dpp_ctrl_ = 0;
  uint32_t dpp_row_mask_ = 0xF;
  uint32_t dpp_bank_mask_ = 0xF;
  uint32_t dpp_bound_ctrl_ = 0;
  std::unique_ptr<DppOperand> dpp_src0_;
  std::unique_ptr<DppOperand> dpp_src1_;
  uint32_t sdwa_src0_sel_ = amdgpu::sdwa::DWORD;
  bool sdwa_src0_sext_ = false;
  uint32_t sdwa_src1_sel_ = amdgpu::sdwa::DWORD;
  bool sdwa_src1_sext_ = false;
  uint32_t sdwa_dst_sel_ = amdgpu::sdwa::DWORD;
  uint32_t sdwa_dst_unused_ = 0;
  bool sdwa_clamp_ = false;
};

class Vop3 : public IsaInstruction<Isa> {
public:
  Vop3(std::string_view mnemonic, const Vop3MachineInst *inst, ExecuteFn exec_fn);
  bool has_lit_0();
  bool has_lit_1();
  bool has_lit_0_has_lit_1();
  bool has_lit_2();
  bool has_lit_0_has_lit_2();
  bool has_lit_1_has_lit_2();
  bool has_lit_0_has_lit_1_has_lit_2();
  using OpEncoding = Vop3MachineInst;
  const OpEncoding inst_;
};

class Vop3p : public IsaInstruction<Isa> {
public:
  Vop3p(std::string_view mnemonic, const Vop3pMachineInst *inst, ExecuteFn exec_fn);
  bool has_lit_0();
  bool has_lit_1();
  bool has_lit_0_has_lit_1();
  bool has_lit_2();
  bool has_lit_0_has_lit_2();
  bool has_lit_1_has_lit_2();
  bool has_lit_0_has_lit_1_has_lit_2();
  using OpEncoding = Vop3pMachineInst;
  const OpEncoding inst_;
};

class Vinterp : public IsaInstruction<Isa> {
public:
  Vinterp(std::string_view mnemonic, const VinterpMachineInst *inst, ExecuteFn exec_fn);
  using OpEncoding = VinterpMachineInst;
  const OpEncoding inst_;
};

class Ldsdir : public IsaInstruction<Isa> {
public:
  Ldsdir(std::string_view mnemonic, const LdsdirMachineInst *inst, ExecuteFn exec_fn);
  bool default_encoding();
  using OpEncoding = LdsdirMachineInst;
  const OpEncoding inst_;
};

class Ds : public IsaInstruction<Isa> {
public:
  Ds(std::string_view mnemonic, const DsMachineInst *inst, ExecuteFn exec_fn);
  using OpEncoding = DsMachineInst;
  const OpEncoding inst_;
};

class Mubuf : public IsaInstruction<Isa> {
public:
  Mubuf(std::string_view mnemonic, const MubufMachineInst *inst, ExecuteFn exec_fn);
  void build_modifiers(std::string &out) const override;
  using OpEncoding = MubufMachineInst;
  const OpEncoding inst_;
};

class Mtbuf : public IsaInstruction<Isa> {
public:
  Mtbuf(std::string_view mnemonic, const MtbufMachineInst *inst, ExecuteFn exec_fn);
  void build_modifiers(std::string &out) const override;
  using OpEncoding = MtbufMachineInst;
  const OpEncoding inst_;
};

class Mimg : public IsaInstruction<Isa> {
public:
  Mimg(std::string_view mnemonic, const MimgMachineInst *inst, ExecuteFn exec_fn);
  bool has_nsa();
  using OpEncoding = MimgMachineInst;
  const OpEncoding inst_;
};

class Exp : public IsaInstruction<Isa> {
public:
  Exp(std::string_view mnemonic, const ExpMachineInst *inst, ExecuteFn exec_fn);
  using OpEncoding = ExpMachineInst;
  const OpEncoding inst_;
};

class Flat : public IsaInstruction<Isa> {
public:
  Flat(std::string_view mnemonic, const FlatMachineInst *inst, ExecuteFn exec_fn);
  void build_modifiers(std::string &out) const override;
  void implicit_uses(RegisterSet &uses) const override;
  using OpEncoding = FlatMachineInst;
  const OpEncoding inst_;
  std::string owned_mnemonic_;
};

class Vop3SdstEnc : public IsaInstruction<Isa> {
public:
  Vop3SdstEnc(std::string_view mnemonic, const Vop3SdstEncMachineInst *inst, ExecuteFn exec_fn);
  using OpEncoding = Vop3SdstEncMachineInst;
  const OpEncoding inst_;
};

} // namespace rdna3_5
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_RDNA3_5_ENCODINGS_H_
