// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna3_5/sop2.h"
#include "rocjitsu/isa/arch/amdgpu/shared/execute_shared.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna3_5 {

SAddU32Sop2::SAddU32Sop2(const MachineInst *inst)
    : Sop2("s_add_u32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAddU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAddU32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_add_u32_sop2(*this, wf); }

SSubU32Sop2::SSubU32Sop2(const MachineInst *inst)
    : Sop2("s_sub_u32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSubU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SSubU32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_sub_u32_sop2(*this, wf); }

SAddI32Sop2::SAddI32Sop2(const MachineInst *inst)
    : Sop2("s_add_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAddI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAddI32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_add_i32_sop2(*this, wf); }

SSubI32Sop2::SSubI32Sop2(const MachineInst *inst)
    : Sop2("s_sub_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSubI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SSubI32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_sub_i32_sop2(*this, wf); }

SAddcU32Sop2::SAddcU32Sop2(const MachineInst *inst)
    : Sop2("s_addc_u32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAddcU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAddcU32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_addc_u32_sop2(*this, wf);
}

SSubbU32Sop2::SSubbU32Sop2(const MachineInst *inst)
    : Sop2("s_subb_u32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSubbU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SSubbU32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_subb_u32_sop2(*this, wf);
}

SAbsdiffI32Sop2::SAbsdiffI32Sop2(const MachineInst *inst)
    : Sop2("s_absdiff_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAbsdiffI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAbsdiffI32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_absdiff_i32_sop2(*this, wf);
}

SLshlB32Sop2::SLshlB32Sop2(const MachineInst *inst)
    : Sop2("s_lshl_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SLshlB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SLshlB32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_lshl_b32_sop2(*this, wf);
}

SLshlB64Sop2::SLshlB64Sop2(const MachineInst *inst)
    : Sop2("s_lshl_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SLshlB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SLshlB64Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_lshl_b64_sop2(*this, wf);
}

SLshrB32Sop2::SLshrB32Sop2(const MachineInst *inst)
    : Sop2("s_lshr_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SLshrB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SLshrB32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_lshr_b32_sop2(*this, wf);
}

SLshrB64Sop2::SLshrB64Sop2(const MachineInst *inst)
    : Sop2("s_lshr_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SLshrB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SLshrB64Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_lshr_b64_sop2(*this, wf);
}

SAshrI32Sop2::SAshrI32Sop2(const MachineInst *inst)
    : Sop2("s_ashr_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAshrI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAshrI32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_ashr_i32_sop2(*this, wf);
}

SAshrI64Sop2::SAshrI64Sop2(const MachineInst *inst)
    : Sop2("s_ashr_i64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAshrI64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAshrI64Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_ashr_i64_sop2(*this, wf);
}

SLshl1AddU32Sop2::SLshl1AddU32Sop2(const MachineInst *inst)
    : Sop2("s_lshl1_add_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SLshl1AddU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SLshl1AddU32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_lshl1_add_u32_sop2(*this, wf);
}

SLshl2AddU32Sop2::SLshl2AddU32Sop2(const MachineInst *inst)
    : Sop2("s_lshl2_add_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SLshl2AddU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SLshl2AddU32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_lshl2_add_u32_sop2(*this, wf);
}

SLshl3AddU32Sop2::SLshl3AddU32Sop2(const MachineInst *inst)
    : Sop2("s_lshl3_add_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SLshl3AddU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SLshl3AddU32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_lshl3_add_u32_sop2(*this, wf);
}

SLshl4AddU32Sop2::SLshl4AddU32Sop2(const MachineInst *inst)
    : Sop2("s_lshl4_add_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SLshl4AddU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SLshl4AddU32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_lshl4_add_u32_sop2(*this, wf);
}

SMinI32Sop2::SMinI32Sop2(const MachineInst *inst)
    : Sop2("s_min_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMinI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMinI32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_min_i32_sop2(*this, wf); }

SMinU32Sop2::SMinU32Sop2(const MachineInst *inst)
    : Sop2("s_min_u32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMinU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMinU32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_min_u32_sop2(*this, wf); }

SMaxI32Sop2::SMaxI32Sop2(const MachineInst *inst)
    : Sop2("s_max_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMaxI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMaxI32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_max_i32_sop2(*this, wf); }

SMaxU32Sop2::SMaxU32Sop2(const MachineInst *inst)
    : Sop2("s_max_u32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMaxU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMaxU32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_max_u32_sop2(*this, wf); }

SAndB32Sop2::SAndB32Sop2(const MachineInst *inst)
    : Sop2("s_and_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAndB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAndB32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_and_b32_sop2(*this, wf); }

SAndB64Sop2::SAndB64Sop2(const MachineInst *inst)
    : Sop2("s_and_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAndB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAndB64Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_and_b64_sop2(*this, wf); }

SOrB32Sop2::SOrB32Sop2(const MachineInst *inst)
    : Sop2("s_or_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SOrB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SOrB32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_or_b32_sop2(*this, wf); }

SOrB64Sop2::SOrB64Sop2(const MachineInst *inst)
    : Sop2("s_or_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SOrB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SOrB64Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_or_b64_sop2(*this, wf); }

SXorB32Sop2::SXorB32Sop2(const MachineInst *inst)
    : Sop2("s_xor_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SXorB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SXorB32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_xor_b32_sop2(*this, wf); }

SXorB64Sop2::SXorB64Sop2(const MachineInst *inst)
    : Sop2("s_xor_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SXorB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SXorB64Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_xor_b64_sop2(*this, wf); }

SNandB32Sop2::SNandB32Sop2(const MachineInst *inst)
    : Sop2("s_nand_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNandB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SNandB32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_nand_b32_sop2(*this, wf);
}

SNandB64Sop2::SNandB64Sop2(const MachineInst *inst)
    : Sop2("s_nand_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNandB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SNandB64Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_nand_b64_sop2(*this, wf);
}

SNorB32Sop2::SNorB32Sop2(const MachineInst *inst)
    : Sop2("s_nor_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNorB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SNorB32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_nor_b32_sop2(*this, wf); }

SNorB64Sop2::SNorB64Sop2(const MachineInst *inst)
    : Sop2("s_nor_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNorB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SNorB64Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_nor_b64_sop2(*this, wf); }

SXnorB32Sop2::SXnorB32Sop2(const MachineInst *inst)
    : Sop2("s_xnor_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SXnorB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SXnorB32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_xnor_b32_sop2(*this, wf);
}

SXnorB64Sop2::SXnorB64Sop2(const MachineInst *inst)
    : Sop2("s_xnor_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SXnorB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SXnorB64Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_xnor_b64_sop2(*this, wf);
}

SAndNot1B32Sop2::SAndNot1B32Sop2(const MachineInst *inst)
    : Sop2("s_and_not1_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot1B32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot1B32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SAndNot1B64Sop2::SAndNot1B64Sop2(const MachineInst *inst)
    : Sop2("s_and_not1_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot1B64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot1B64Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SOrNot1B32Sop2::SOrNot1B32Sop2(const MachineInst *inst)
    : Sop2("s_or_not1_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrNot1B32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SOrNot1B32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SOrNot1B64Sop2::SOrNot1B64Sop2(const MachineInst *inst)
    : Sop2("s_or_not1_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrNot1B64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SOrNot1B64Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SBfeU32Sop2::SBfeU32Sop2(const MachineInst *inst)
    : Sop2("s_bfe_u32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBfeU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SBfeU32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_bfe_u32_sop2(*this, wf); }

SBfeI32Sop2::SBfeI32Sop2(const MachineInst *inst)
    : Sop2("s_bfe_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBfeI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SBfeI32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_bfe_i32_sop2(*this, wf); }

SBfeU64Sop2::SBfeU64Sop2(const MachineInst *inst)
    : Sop2("s_bfe_u64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBfeU64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SBfeU64Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_bfe_u64_sop2(*this, wf); }

SBfeI64Sop2::SBfeI64Sop2(const MachineInst *inst)
    : Sop2("s_bfe_i64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBfeI64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SBfeI64Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_bfe_i64_sop2(*this, wf); }

SBfmB32Sop2::SBfmB32Sop2(const MachineInst *inst)
    : Sop2("s_bfm_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBfmB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SBfmB32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_bfm_b32_sop2(*this, wf); }

SBfmB64Sop2::SBfmB64Sop2(const MachineInst *inst)
    : Sop2("s_bfm_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBfmB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SBfmB64Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_bfm_b64_sop2(*this, wf); }

SMulI32Sop2::SMulI32Sop2(const MachineInst *inst)
    : Sop2("s_mul_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMulI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMulI32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_mul_i32_sop2(*this, wf); }

SMulHiU32Sop2::SMulHiU32Sop2(const MachineInst *inst)
    : Sop2("s_mul_hi_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMulHiU32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMulHiU32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_mul_hi_u32_sop2(*this, wf);
}

SMulHiI32Sop2::SMulHiI32Sop2(const MachineInst *inst)
    : Sop2("s_mul_hi_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMulHiI32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMulHiI32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_mul_hi_i32_sop2(*this, wf);
}

SCselectB32Sop2::SCselectB32Sop2(const MachineInst *inst)
    : Sop2("s_cselect_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCselectB32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SCselectB32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cselect_b32_sop2(*this, wf);
}

SCselectB64Sop2::SCselectB64Sop2(const MachineInst *inst)
    : Sop2("s_cselect_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCselectB64Sop2>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SCselectB64Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cselect_b64_sop2(*this, wf);
}

SPackLlB32B16Sop2::SPackLlB32B16Sop2(const MachineInst *inst)
    : Sop2("s_pack_ll_b32_b16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SPackLlB32B16Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SPackLlB32B16Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_pack_ll_b32_b16_sop2(*this, wf);
}

SPackLhB32B16Sop2::SPackLhB32B16Sop2(const MachineInst *inst)
    : Sop2("s_pack_lh_b32_b16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SPackLhB32B16Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SPackLhB32B16Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_pack_lh_b32_b16_sop2(*this, wf);
}

SPackHhB32B16Sop2::SPackHhB32B16Sop2(const MachineInst *inst)
    : Sop2("s_pack_hh_b32_b16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SPackHhB32B16Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SPackHhB32B16Sop2::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_pack_hh_b32_b16_sop2(*this, wf);
}

SPackHlB32B16Sop2::SPackHlB32B16Sop2(const MachineInst *inst)
    : Sop2("s_pack_hl_b32_b16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SPackHlB32B16Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SPackHlB32B16Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SAddF32Sop2::SAddF32Sop2(const MachineInst *inst)
    : Sop2("s_add_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAddF32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAddF32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_add_f32_sop2(*this, wf); }

SSubF32Sop2::SSubF32Sop2(const MachineInst *inst)
    : Sop2("s_sub_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSubF32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SSubF32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_sub_f32_sop2(*this, wf); }

SMinF32Sop2::SMinF32Sop2(const MachineInst *inst)
    : Sop2("s_min_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMinF32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMinF32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  float result = std::min(std::bit_cast<float>(ssrc0.read_scalar(wf)),
                          std::bit_cast<float>(ssrc1.read_scalar(wf)));
  sdst.write_scalar(wf, std::bit_cast<uint32_t>(result));
}

SMaxF32Sop2::SMaxF32Sop2(const MachineInst *inst)
    : Sop2("s_max_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMaxF32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMaxF32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  float result = std::max(std::bit_cast<float>(ssrc0.read_scalar(wf)),
                          std::bit_cast<float>(ssrc1.read_scalar(wf)));
  sdst.write_scalar(wf, std::bit_cast<uint32_t>(result));
}

SMulF32Sop2::SMulF32Sop2(const MachineInst *inst)
    : Sop2("s_mul_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMulF32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMulF32Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_mul_f32_sop2(*this, wf); }

SFmaakF32Sop2::SFmaakF32Sop2(const MachineInst *inst)
    : Sop2("s_fmaak_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFmaakF32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SFmaakF32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SFmamkF32Sop2::SFmamkF32Sop2(const MachineInst *inst)
    : Sop2("s_fmamk_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFmamkF32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SFmamkF32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SFmacF32Sop2::SFmacF32Sop2(const MachineInst *inst)
    : Sop2("s_fmac_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SFmacF32Sop2>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  src_operands_[2] = &ssrc1;
  num_src_ = 3;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SFmacF32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SCvtPkRtzF16F32Sop2::SCvtPkRtzF16F32Sop2(const MachineInst *inst)
    : Sop2("s_cvt_pk_rtz_f16_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCvtPkRtzF16F32Sop2>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SCvtPkRtzF16F32Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SAddF16Sop2::SAddF16Sop2(const MachineInst *inst)
    : Sop2("s_add_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAddF16Sop2>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SAddF16Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_add_f16_sop2(*this, wf); }

SSubF16Sop2::SSubF16Sop2(const MachineInst *inst)
    : Sop2("s_sub_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSubF16Sop2>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SSubF16Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_sub_f16_sop2(*this, wf); }

SMinF16Sop2::SMinF16Sop2(const MachineInst *inst)
    : Sop2("s_min_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMinF16Sop2>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMinF16Sop2::execute_impl(amdgpu::Wavefront &wf) {
  float result = std::min(util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))),
                          util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))));
  sdst.write_scalar(wf, util::f32_to_f16(result));
}

SMaxF16Sop2::SMaxF16Sop2(const MachineInst *inst)
    : Sop2("s_max_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMaxF16Sop2>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMaxF16Sop2::execute_impl(amdgpu::Wavefront &wf) {
  float result = std::max(util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))),
                          util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))));
  sdst.write_scalar(wf, util::f32_to_f16(result));
}

SMulF16Sop2::SMulF16Sop2(const MachineInst *inst)
    : Sop2("s_mul_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMulF16Sop2>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SMulF16Sop2::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_mul_f16_sop2(*this, wf); }

SFmacF16Sop2::SFmacF16Sop2(const MachineInst *inst)
    : Sop2("s_fmac_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SFmacF16Sop2>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  src_operands_[2] = &ssrc1;
  num_src_ = 3;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop2InstLiteralMachineInst *>(inst)->simm32));
}

void SFmacF16Sop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

} // namespace rdna3_5
} // namespace rocjitsu
