// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna4/sopk.h"
#include "rocjitsu/isa/arch/amdgpu/shared/execute_shared.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include "util/log.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna4 {

SMovkI32Sopk::SMovkI32Sopk(const MachineInst *inst)
    : Sopk("s_movk_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMovkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 1;
}

void SMovkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_movk_i32_sopk(*this, wf);
}

SVersionSopk::SVersionSopk(const MachineInst *inst)
    : Sopk("s_version", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SVersionSopk>()),
      simm16(16, OperandType::OPR_VERSION, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SVersionSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SCmovkI32Sopk::SCmovkI32Sopk(const MachineInst *inst)
    : Sopk("s_cmovk_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmovkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 1;
  flags_ |= PREDICATED_DEF;
}

void SCmovkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmovk_i32_sopk(*this, wf);
}

SAddkCoI32Sopk::SAddkCoI32Sopk(const MachineInst *inst)
    : Sopk("s_addk_co_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAddkCoI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 1;
}

void SAddkCoI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SMulkI32Sopk::SMulkI32Sopk(const MachineInst *inst)
    : Sopk("s_mulk_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMulkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 1;
}

void SMulkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_mulk_i32_sopk(*this, wf);
}

SGetregB32Sopk::SGetregB32Sopk(const MachineInst *inst)
    : Sopk("s_getreg_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SGetregB32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 1;
}

void SGetregB32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_getreg_b32_sopk(*this, wf);
}

SSetregB32Sopk::SSetregB32Sopk(const MachineInst *inst)
    : Sopk("s_setreg_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetregB32Sopk>()),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst) {
  dst_operands_[0] = &simm16;
  src_operands_[0] = &sdst;
  num_src_ = 1;
  num_dst_ = 1;
}

void SSetregB32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_setreg_b32_sopk(*this, wf);
}

SSetregImm32B32Sopk::SSetregImm32B32Sopk(const MachineInst *inst)
    : Sopk("s_setreg_imm32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetregImm32B32Sopk>()),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &simm16;
  num_src_ = 0;
  num_dst_ = 1;
}

void SSetregImm32B32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_setreg_imm32_b32_sopk(*this, wf);
}

SCallB64Sopk::SCallB64Sopk(const MachineInst *inst)
    : Sopk("s_call_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCallB64Sopk>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 1;
  flags_ |= INDIRECT_CALL;
}

void SCallB64Sopk::execute_impl(amdgpu::Wavefront &wf) {
  sdst.write_scalar64(wf, wf.pc + size_);
  int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
  wf.pc = wf.pc + static_cast<int64_t>(offset) * 4 - size_;
}

} // namespace rdna4
} // namespace rocjitsu
