// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna3/sopk.h"
#include "rocjitsu/isa/arch/amdgpu/shared/execute_shared.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include "util/log.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna3 {

SMovkI32Sopk::SMovkI32Sopk(const MachineInst *inst)
    : Sopk("s_movk_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMovkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 1;
}

void SMovkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_movk_i32_sopk(*this, wf);
}

SVersionSopk::SVersionSopk(const MachineInst *inst)
    : Sopk("s_version", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SVersionSopk>()),
      simm16(16, OperandType::OPR_VERSION, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SVersionSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SCmovkI32Sopk::SCmovkI32Sopk(const MachineInst *inst)
    : Sopk("s_cmovk_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmovkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 1;
  flags_ |= PREDICATED_DEF;
}

void SCmovkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmovk_i32_sopk(*this, wf);
}

SCmpkEqI32Sopk::SCmpkEqI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_eq_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkEqI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkEqI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_eq_i32_sopk(*this, wf);
}

SCmpkLgI32Sopk::SCmpkLgI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_lg_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLgI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkLgI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_lg_i32_sopk(*this, wf);
}

SCmpkGtI32Sopk::SCmpkGtI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_gt_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkGtI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkGtI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_gt_i32_sopk(*this, wf);
}

SCmpkGeI32Sopk::SCmpkGeI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_ge_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkGeI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkGeI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_ge_i32_sopk(*this, wf);
}

SCmpkLtI32Sopk::SCmpkLtI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_lt_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLtI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkLtI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_lt_i32_sopk(*this, wf);
}

SCmpkLeI32Sopk::SCmpkLeI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_le_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLeI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkLeI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_le_i32_sopk(*this, wf);
}

SCmpkEqU32Sopk::SCmpkEqU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_eq_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkEqU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkEqU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_eq_u32_sopk(*this, wf);
}

SCmpkLgU32Sopk::SCmpkLgU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_lg_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLgU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkLgU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_lg_u32_sopk(*this, wf);
}

SCmpkGtU32Sopk::SCmpkGtU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_gt_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkGtU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkGtU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_gt_u32_sopk(*this, wf);
}

SCmpkGeU32Sopk::SCmpkGeU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_ge_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkGeU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkGeU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_ge_u32_sopk(*this, wf);
}

SCmpkLtU32Sopk::SCmpkLtU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_lt_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLtU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkLtU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_lt_u32_sopk(*this, wf);
}

SCmpkLeU32Sopk::SCmpkLeU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_le_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLeU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
}

void SCmpkLeU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmpk_le_u32_sopk(*this, wf);
}

SAddkI32Sopk::SAddkI32Sopk(const MachineInst *inst)
    : Sopk("s_addk_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAddkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 1;
}

void SAddkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_addk_i32_sopk(*this, wf);
}

SMulkI32Sopk::SMulkI32Sopk(const MachineInst *inst)
    : Sopk("s_mulk_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMulkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 1;
}

void SMulkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_mulk_i32_sopk(*this, wf);
}

SGetregB32Sopk::SGetregB32Sopk(const MachineInst *inst)
    : Sopk("s_getreg_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SGetregB32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 1;
}

void SGetregB32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_getreg_b32_sopk(*this, wf);
}

SSetregB32Sopk::SSetregB32Sopk(const MachineInst *inst)
    : Sopk("s_setreg_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetregB32Sopk>()),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst) {
  dst_operands_[0] = &simm16;
  src_operands_[0] = &sdst;
  num_src_ = 1;
  num_dst_ = 1;
}

void SSetregB32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_setreg_b32_sopk(*this, wf);
}

SSetregImm32B32Sopk::SSetregImm32B32Sopk(const MachineInst *inst)
    : Sopk("s_setreg_imm32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetregImm32B32Sopk>()),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &simm16;
  num_src_ = 0;
  num_dst_ = 1;
}

void SSetregImm32B32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_setreg_imm32_b32_sopk(*this, wf);
}

SCallB64Sopk::SCallB64Sopk(const MachineInst *inst)
    : Sopk("s_call_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCallB64Sopk>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 1;
  flags_ |= INDIRECT_CALL;
}

void SCallB64Sopk::execute_impl(amdgpu::Wavefront &wf) {
  sdst.write_scalar64(wf, wf.pc + size_);
  int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
  wf.pc = wf.pc + static_cast<int64_t>(offset) * 4 - size_;
}

SWaitcntVscntSopk::SWaitcntVscntSopk(const MachineInst *inst)
    : Sopk("s_waitcnt_vscnt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntVscntSopk>()),
      sdst(32, OperandType::OPR_SDST_NULL, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
  flags_ |= WAITCNT;
}

void SWaitcntVscntSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SWaitcntVmcntSopk::SWaitcntVmcntSopk(const MachineInst *inst)
    : Sopk("s_waitcnt_vmcnt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntVmcntSopk>()),
      sdst(32, OperandType::OPR_SDST_NULL, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
  flags_ |= WAITCNT;
}

void SWaitcntVmcntSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SWaitcntExpcntSopk::SWaitcntExpcntSopk(const MachineInst *inst)
    : Sopk("s_waitcnt_expcnt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntExpcntSopk>()),
      sdst(32, OperandType::OPR_SDST_NULL, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
  flags_ |= WAITCNT;
}

void SWaitcntExpcntSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SWaitcntLgkmcntSopk::SWaitcntLgkmcntSopk(const MachineInst *inst)
    : Sopk("s_waitcnt_lgkmcnt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntLgkmcntSopk>()),
      sdst(32, OperandType::OPR_SDST_NULL, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  num_src_ = 2;
  num_dst_ = 0;
  flags_ |= WAITCNT;
}

void SWaitcntLgkmcntSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

} // namespace rdna3
} // namespace rocjitsu
