// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/cdna1/sop1.h"
#include "rocjitsu/isa/arch/amdgpu/shared/execute_shared.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include "util/log.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <format>
#include <limits>

namespace rocjitsu {
namespace cdna1 {

SMovB32Sop1::SMovB32Sop1(const MachineInst *inst)
    : Sop1("s_mov_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMovB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovB32Sop1::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_mov_b32_sop1(*this, wf); }

SMovB64Sop1::SMovB64Sop1(const MachineInst *inst)
    : Sop1("s_mov_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMovB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovB64Sop1::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_mov_b64_sop1(*this, wf); }

SCmovB32Sop1::SCmovB32Sop1(const MachineInst *inst)
    : Sop1("s_cmov_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCmovB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
  flags_ |= PREDICATED_DEF;
}

void SCmovB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmov_b32_sop1(*this, wf);
}

SCmovB64Sop1::SCmovB64Sop1(const MachineInst *inst)
    : Sop1("s_cmov_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCmovB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
  flags_ |= PREDICATED_DEF;
}

void SCmovB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cmov_b64_sop1(*this, wf);
}

SNotB32Sop1::SNotB32Sop1(const MachineInst *inst)
    : Sop1("s_not_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNotB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNotB32Sop1::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_not_b32_sop1(*this, wf); }

SNotB64Sop1::SNotB64Sop1(const MachineInst *inst)
    : Sop1("s_not_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNotB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNotB64Sop1::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_not_b64_sop1(*this, wf); }

SWqmB32Sop1::SWqmB32Sop1(const MachineInst *inst)
    : Sop1("s_wqm_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SWqmB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SWqmB32Sop1::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_wqm_b32_sop1(*this, wf); }

SWqmB64Sop1::SWqmB64Sop1(const MachineInst *inst)
    : Sop1("s_wqm_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SWqmB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SWqmB64Sop1::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_wqm_b64_sop1(*this, wf); }

SBrevB32Sop1::SBrevB32Sop1(const MachineInst *inst)
    : Sop1("s_brev_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBrevB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBrevB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_brev_b32_sop1(*this, wf);
}

SBrevB64Sop1::SBrevB64Sop1(const MachineInst *inst)
    : Sop1("s_brev_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBrevB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBrevB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_brev_b64_sop1(*this, wf);
}

SBcnt0I32B32Sop1::SBcnt0I32B32Sop1(const MachineInst *inst)
    : Sop1("s_bcnt0_i32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBcnt0I32B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBcnt0I32B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_bcnt0_i32_b32_sop1(*this, wf);
}

SBcnt0I32B64Sop1::SBcnt0I32B64Sop1(const MachineInst *inst)
    : Sop1("s_bcnt0_i32_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBcnt0I32B64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBcnt0I32B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_bcnt0_i32_b64_sop1(*this, wf);
}

SBcnt1I32B32Sop1::SBcnt1I32B32Sop1(const MachineInst *inst)
    : Sop1("s_bcnt1_i32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBcnt1I32B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBcnt1I32B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_bcnt1_i32_b32_sop1(*this, wf);
}

SBcnt1I32B64Sop1::SBcnt1I32B64Sop1(const MachineInst *inst)
    : Sop1("s_bcnt1_i32_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBcnt1I32B64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBcnt1I32B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_bcnt1_i32_b64_sop1(*this, wf);
}

SFf0I32B32Sop1::SFf0I32B32Sop1(const MachineInst *inst)
    : Sop1("s_ff0_i32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFf0I32B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFf0I32B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_ff0_i32_b32_sop1(*this, wf);
}

SFf0I32B64Sop1::SFf0I32B64Sop1(const MachineInst *inst)
    : Sop1("s_ff0_i32_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFf0I32B64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFf0I32B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_ff0_i32_b64_sop1(*this, wf);
}

SFf1I32B32Sop1::SFf1I32B32Sop1(const MachineInst *inst)
    : Sop1("s_ff1_i32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFf1I32B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFf1I32B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_ff1_i32_b32_sop1(*this, wf);
}

SFf1I32B64Sop1::SFf1I32B64Sop1(const MachineInst *inst)
    : Sop1("s_ff1_i32_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFf1I32B64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFf1I32B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_ff1_i32_b64_sop1(*this, wf);
}

SFlbitI32B32Sop1::SFlbitI32B32Sop1(const MachineInst *inst)
    : Sop1("s_flbit_i32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFlbitI32B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFlbitI32B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_flbit_i32_b32_sop1(*this, wf);
}

SFlbitI32B64Sop1::SFlbitI32B64Sop1(const MachineInst *inst)
    : Sop1("s_flbit_i32_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFlbitI32B64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFlbitI32B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_flbit_i32_b64_sop1(*this, wf);
}

SFlbitI32Sop1::SFlbitI32Sop1(const MachineInst *inst)
    : Sop1("s_flbit_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFlbitI32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFlbitI32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_flbit_i32_sop1(*this, wf);
}

SFlbitI32I64Sop1::SFlbitI32I64Sop1(const MachineInst *inst)
    : Sop1("s_flbit_i32_i64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFlbitI32I64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFlbitI32I64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_flbit_i32_i64_sop1(*this, wf);
}

SSextI32I8Sop1::SSextI32I8Sop1(const MachineInst *inst)
    : Sop1("s_sext_i32_i8", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSextI32I8Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SSextI32I8Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_sext_i32_i8_sop1(*this, wf);
}

SSextI32I16Sop1::SSextI32I16Sop1(const MachineInst *inst)
    : Sop1("s_sext_i32_i16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSextI32I16Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SSextI32I16Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_sext_i32_i16_sop1(*this, wf);
}

SBitset0B32Sop1::SBitset0B32Sop1(const MachineInst *inst)
    : Sop1("s_bitset0_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitset0B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitset0B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SBitset0B64Sop1::SBitset0B64Sop1(const MachineInst *inst)
    : Sop1("s_bitset0_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitset0B64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitset0B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SBitset1B32Sop1::SBitset1B32Sop1(const MachineInst *inst)
    : Sop1("s_bitset1_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitset1B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitset1B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SBitset1B64Sop1::SBitset1B64Sop1(const MachineInst *inst)
    : Sop1("s_bitset1_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitset1B64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitset1B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SGetpcB64Sop1::SGetpcB64Sop1(const MachineInst *inst)
    : Sop1("s_getpc_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SGetpcB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst) {
  dst_operands_[0] = &sdst;
  num_src_ = 0;
  num_dst_ = 1;
}

void SGetpcB64Sop1::execute_impl(amdgpu::Wavefront &wf) { sdst.write_scalar64(wf, wf.pc + size_); }

SSetpcB64Sop1::SSetpcB64Sop1(const MachineInst *inst)
    : Sop1("s_setpc_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetpcB64Sop1>()),
      ssrc0(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
  flags_ |= INDIRECT_BRANCH;
}

void SSetpcB64Sop1::execute_impl(amdgpu::Wavefront &wf) { wf.pc = ssrc0.read_scalar64(wf) - size_; }

SSwappcB64Sop1::SSwappcB64Sop1(const MachineInst *inst)
    : Sop1("s_swappc_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSwappcB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
  flags_ |= INDIRECT_CALL;
}

void SSwappcB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t next_pc = wf.pc + size_;
  wf.pc = ssrc0.read_scalar64(wf) - size_;
  sdst.write_scalar64(wf, next_pc);
}

SRfeB64Sop1::SRfeB64Sop1(const MachineInst *inst)
    : Sop1("s_rfe_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SRfeB64Sop1>()),
      ssrc0(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SRfeB64Sop1::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_rfe_b64_sop1(*this, wf); }

SAndSaveexecB64Sop1::SAndSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_and_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_and_saveexec_b64_sop1(*this, wf);
}

SOrSaveexecB64Sop1::SOrSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_or_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_or_saveexec_b64_sop1(*this, wf);
}

SXorSaveexecB64Sop1::SXorSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_xor_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SXorSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SXorSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_xor_saveexec_b64_sop1(*this, wf);
}

SAndn2SaveexecB64Sop1::SAndn2SaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_andn2_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndn2SaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndn2SaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_andn2_saveexec_b64_sop1(*this, wf);
}

SOrn2SaveexecB64Sop1::SOrn2SaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_orn2_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrn2SaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrn2SaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_orn2_saveexec_b64_sop1(*this, wf);
}

SNandSaveexecB64Sop1::SNandSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_nand_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SNandSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNandSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_nand_saveexec_b64_sop1(*this, wf);
}

SNorSaveexecB64Sop1::SNorSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_nor_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SNorSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNorSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_nor_saveexec_b64_sop1(*this, wf);
}

SXnorSaveexecB64Sop1::SXnorSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_xnor_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SXnorSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SXnorSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_xnor_saveexec_b64_sop1(*this, wf);
}

SQuadmaskB32Sop1::SQuadmaskB32Sop1(const MachineInst *inst)
    : Sop1("s_quadmask_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SQuadmaskB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SQuadmaskB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_quadmask_b32_sop1(*this, wf);
}

SQuadmaskB64Sop1::SQuadmaskB64Sop1(const MachineInst *inst)
    : Sop1("s_quadmask_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SQuadmaskB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SQuadmaskB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_quadmask_b64_sop1(*this, wf);
}

SMovrelsB32Sop1::SMovrelsB32Sop1(const MachineInst *inst)
    : Sop1("s_movrels_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovrelsB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovrelsB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SMovrelsB64Sop1::SMovrelsB64Sop1(const MachineInst *inst)
    : Sop1("s_movrels_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovrelsB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovrelsB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SMovreldB32Sop1::SMovreldB32Sop1(const MachineInst *inst)
    : Sop1("s_movreld_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovreldB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovreldB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SMovreldB64Sop1::SMovreldB64Sop1(const MachineInst *inst)
    : Sop1("s_movreld_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovreldB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovreldB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SCbranchJoinSop1::SCbranchJoinSop1(const MachineInst *inst)
    : Sop1("s_cbranch_join", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchJoinSop1>()),
      ssrc0(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCbranchJoinSop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_cbranch_join_sop1(*this, wf);
}

SAbsI32Sop1::SAbsI32Sop1(const MachineInst *inst)
    : Sop1("s_abs_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAbsI32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAbsI32Sop1::execute_impl(amdgpu::Wavefront &wf) { amdgpu::execute_s_abs_i32_sop1(*this, wf); }

SSetGprIdxIdxSop1::SSetGprIdxIdxSop1(const MachineInst *inst)
    : Sop1("s_set_gpr_idx_idx", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetGprIdxIdxSop1>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SSetGprIdxIdxSop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_set_gpr_idx_idx_sop1(*this, wf);
}

SAndn1SaveexecB64Sop1::SAndn1SaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_andn1_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndn1SaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndn1SaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_andn1_saveexec_b64_sop1(*this, wf);
}

SOrn1SaveexecB64Sop1::SOrn1SaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_orn1_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrn1SaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrn1SaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_orn1_saveexec_b64_sop1(*this, wf);
}

SAndn1WrexecB64Sop1::SAndn1WrexecB64Sop1(const MachineInst *inst)
    : Sop1("s_andn1_wrexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndn1WrexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndn1WrexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_andn1_wrexec_b64_sop1(*this, wf);
}

SAndn2WrexecB64Sop1::SAndn2WrexecB64Sop1(const MachineInst *inst)
    : Sop1("s_andn2_wrexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndn2WrexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndn2WrexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_andn2_wrexec_b64_sop1(*this, wf);
}

SBitreplicateB64B32Sop1::SBitreplicateB64B32Sop1(const MachineInst *inst)
    : Sop1("s_bitreplicate_b64_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitreplicateB64B32Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  num_src_ = 1;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitreplicateB64B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

} // namespace cdna1
} // namespace rocjitsu
