name: TheRock Test Packages

on:
  workflow_call:
    inputs:
      projects_to_test:
        type: string
      amdgpu_families:
        type: string
      test_runs_on:
        type: string
      platform:
        type: string
      artifact_run_id:
        type: string
        default: ""
      sanity_check_only_for_family:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  configure_test_matrix:
    name: "Configure test matrix"
    runs-on: ${{ inputs.test_runs_on }}
    if: ${{ inputs.test_runs_on != '' }}
    outputs:
      components: ${{ steps.configure.outputs.components }}
      platform: ${{ steps.configure.outputs.platform }}
      sanity_component: ${{ steps.configure.outputs.sanity_component }}
    steps:
      - name: "Fetch 'build_tools' from repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: build_tools
          path: "prejob"
          repository: "ROCm/TheRock"

      # Checkout failure is possible on Windows, as it's the first job on a GPU test runner.
      # Post-job cleanup isn't necessary since no executables are launched in this job.
      - name: Pre-job cleanup processes on Windows
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: . '${{ github.workspace }}\prejob\build_tools\github_actions\cleanup_processes.ps1'

      - name: "Checking out repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: "ROCm/TheRock"
          ref: 910bc0bc9e25ac533f100b343ac03b30562a899a # 2026-05-13 commit

      - name: Setting up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.12

      - name: "Configuring CI options"
        env:
          PROJECTS_TO_TEST: ${{ inputs.projects_to_test }}
          AMDGPU_FAMILIES: ${{ inputs.amdgpu_families }}
          WINDOWS_HIP_ROCR_TESTS: ${{ contains(inputs.projects_to_test, 'hip-tests') }}
        id: configure
        run: python ./build_tools/github_actions/fetch_test_configurations.py

  test_sanity_check:
    name: 'Test Sanity Check'
    needs: configure_test_matrix
    uses: './.github/workflows/therock-test-component.yml'
    with:
      artifact_run_id: ${{ inputs.artifact_run_id }}
      amdgpu_families: ${{ inputs.amdgpu_families }}
      test_runs_on: ${{ inputs.test_runs_on }}
      platform: ${{ needs.configure_test_matrix.outputs.platform }}
      component: ${{ needs.configure_test_matrix.outputs.sanity_component }}

  test_components:
    name: 'Test ${{ matrix.components.job_name }}'
    needs: [test_sanity_check, configure_test_matrix]
    # skip tests if no test matrix to run and sanity check only requested
    if: ${{ needs.configure_test_matrix.outputs.components != '[]' && !inputs.sanity_check_only_for_family }}
    strategy:
      fail-fast: false
      matrix:
        components: ${{ fromJSON(needs.configure_test_matrix.outputs.components) }}
    uses: './.github/workflows/therock-test-component.yml'
    with:
      artifact_run_id: ${{ inputs.artifact_run_id }}
      amdgpu_families: ${{ inputs.amdgpu_families }}
      # If the test requires a multi GPU, use the multi GPU test runner
      # Otherwise, use the standard test runner
      test_runs_on: >-
        ${{
          matrix.components.multi_gpu_runner != '' &&
            matrix.components.multi_gpu_runner ||
            inputs.test_runs_on
        }}
      platform: ${{ needs.configure_test_matrix.outputs.platform }}
      component: ${{ toJSON(matrix.components) }}
